/// Flutter icons CustIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustIcon
///      fonts:
///       - asset: fonts/CustIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustIcon {
  CustIcon._();

  static const _kFontFam = 'CustIcon';
  static const String? _kFontPkg = null;

  static const IconData library_books = IconData(0xe9cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xeb9e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xf549, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
