// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4i2U_ol9rJXcK4z3_syJrZ13i6ydNco0',
    appId: '1:811273257474:web:d9406f7ca351e7d6555d1b',
    messagingSenderId: '811273257474',
    projectId: 'nou-demo-host',
    authDomain: 'nou-demo-host.firebaseapp.com',
    storageBucket: 'nou-demo-host.appspot.com',
    measurementId: 'G-9VLXMCSEJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAPT9Qx0mkjkEefYlPsZg2SqCzrKbxjGM',
    appId: '1:811273257474:android:111a7934fa523705555d1b',
    messagingSenderId: '811273257474',
    projectId: 'nou-demo-host',
    storageBucket: 'nou-demo-host.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUm45iyMEDYXrij0mRidXZQiUJfdFwKcA',
    appId: '1:811273257474:ios:6586686368b29f69555d1b',
    messagingSenderId: '811273257474',
    projectId: 'nou-demo-host',
    storageBucket: 'nou-demo-host.appspot.com',
    iosClientId: '811273257474-8vgpnj1jtl30aqino3d09b146q54879g.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerOpenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUm45iyMEDYXrij0mRidXZQiUJfdFwKcA',
    appId: '1:811273257474:ios:6586686368b29f69555d1b',
    messagingSenderId: '811273257474',
    projectId: 'nou-demo-host',
    storageBucket: 'nou-demo-host.appspot.com',
    iosClientId: '811273257474-8vgpnj1jtl30aqino3d09b146q54879g.apps.googleusercontent.com',
    iosBundleId: 'com.example.registerOpenu',
  );
}
